### ISSUE TITLE
Issues with most of the labs

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-dp100#112]
Unless I'm doing something incredibly wrong, it appears that the majority of the labs have some sort of issue.     Most of them are where  there should be a line such as `compute_target = 'your-compute-cluster'` (which assumes my students have already create a Compute Cluster called 'your-compute-clouster'  *or*  there should be a code block that checks if the cluster exists, and create it if it doesn't, such as in the 4th code block in Lab #7.

However there are other issues, such as Python modules not installed (the lab assumes they are), SQL queries not working, etc.

I've attached a PDF that shows each lab I had a problem with, and a screen shot of the area I had a problem with.   

I've tested this at least 5 times; I apologize if they are my errors.   I'm teaching this class next week, and would love to get the scripts resolved ASAP.

Link to PDF:  [https://1drv.ms/u/s!AmTkqkQ3lAddob8PnWfnW28ouzCVtg?e=TJLhEN](url)

**Comment by madiepev** [comment]
Hi @tylerfarmer1 thank you for reporting this. There currently is a bug with the product which means that new compute instances aren't working properly. I'm waiting for a reply from the product team since they're working on this issue atm but I'll probably implement a workaround to have the labs working in some form. There are other issues already open to address the problems at hand. I can't open your PDF you attached but I'll close this issue for now to consolidate issues. Let me know if you're encountering issues that aren't similar to the issues already open (and know I'll create a workaround for the compute issues).

**Comment by tylerfarmer1** [comment]
Thanks @madiepev....    Many of them are the same issue, but there are a few that are not....   Try copy/paste this text separately into an in-private/incognito session, you should be able to access the PDF.

https://1drv.ms/u/s!AmTkqkQ3lAddob8PnWfnW28ouzCVtg?e=TJLhEN

**Comment by madiepev** [comment]
I still can't access the link (also due to security reasons). I've resolved some issues. If there still are a few that haven't been addressed, could you share screenshots directly in the issues?
