### ISSUE TITLE
Proposal and question

### ISSUE THREAD

**Issue by ed7257** [MicrosoftLearning/mslearn-dp100#47]
1. Proposal for labs  04a / 04b to mention in markdown that  links should be adjusted for windows and have this format: .\data\diabetes2.csv  (code has forward slash:  ./data/diabetes2.csv that causes an error in Windows, I ran under Visual Studio Code)
2. question for lab 03A <Run an experiment script> get stuck in Starting status (Your job is submitted in Azure cloud and we are monitoring to get logs...), not clear why that happens and how to troubleshoot. Any advice? Tried the same with other script in 04B and got the same problem.

**Comment by madiepev** [comment]
@ed7257 please make sure you open the notebooks in the Jupyter application of your Compute Instance as per these instructions: https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/instructions/04-run-experiments.md#open-jupyter. This way, you access the directory on the Compute Instance which runs Linux that should resolve the error you have with the path. Running the notebooks in VS Code requires some extra steps in order to be successful. I'm assuming that's also why you're experiencing an error with lab 3A. Please try again, following the instructions, and let me know if any problem persists.
