### ISSUE TITLE
Notebook's widget not working with Edge

### ISSUE THREAD

**Issue by rlopezgarcia** [MicrosoftLearning/mslearn-dp100#96]
The Jupyter notebooks for the labs, when using the latest version of Microsoft Edge browser, the widget does not display (RunDetails(run).show()). Instead, it sends the message:

**_UserRunWidget(widget_settings={'childWidgetDisplay': 'popup', 'send_telemetry': False, 'log_level': 'INFO', '…**

So, the students are not able to monitor the progress of the jobs within the notebook.

Using Chrome works fine.

**Comment by madiepev** [comment]
It sounds like this is a bug with the product, not the learning content. Please raise a support ticket in Azure to get help on the bug.

**Comment by rlopezgarcia** [comment]
So are you giving me the responsibility, as a third party of solving the issue that I understand that it is not a problem with the course content, but it affects the course delivery which you are responsible.

I would have expected that you would be the ones to contact Azure Support and do the follow up to solve the problem.

**Comment by madiepev** [comment]
I understand it's frustrating. Unfortunately, there is nothing we can do. We can't reproduce the error (tried through multiple accounts in different browsers) which means we can't troubleshoot. Support can't investigate the cause of the problem if the problem doesn't occur within our test environments. That's why the only way to find out the cause of the problem is to raise a support ticket in the workspace where the problem actually occurs. 
The only other advice we can give is ensure you're using the integrated Notebooks experience (as is stated in the instructions), not the Jupyter application. And to ensure you're using a kernel older than 3.10 (so NOT 3.10). Testing worked with kernel 3.8 as shown below:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/48012580/208169005-5c2f3606-c9ee-4bfa-a601-67d09379969c.png">
